description: Image-to-TikZ benchmark

prompts:
  - id: file://prompt.txt
    label: image-to-tikz

providers: 
  - file://providers.yaml


evaluateOptions:
  repeat: 4
  cache: false

defaultTest:
  assert:
    - type: python
      value: file://../assertions/tikz_is_renderable.py
      metric: renderable
    - type: python
      value: file://../assertions/image_structural_similarity.py
      metric: image_ssim
    - type: python
      value: file://../assertions/image_ms_structural_similarity.py
      metric: image_ms_ssim
    - type: python
      value: file://../assertions/image_clip_similarity.py
      metric: clip_similarity
    - type: python
      value: file://../assertions/image_siglip_similarity.py
      metric: siglip_similarity
    - type: python
      value: file://../assertions/image_lpips.py
      metric: lpips_similarity
    - type: python
      value: file://../assertions/image_dreamsim.py
      metric: dreamsim_similarity
    - type: python
      value: file://../assertions/image_dists.py
      metric: dists_similarity
    - type: python
      value: file://../assertions/tikz_crystalbleu.py
      metric: crystalbleu
    - type: python
      value: file://../assertions/tikz_ted.py
      metric: ted_similarity
    - type: python
      value: file://../assertions/tikz_relative_length_output_reference.py
      metric: relative_length_similarity
    - type: python
      value: file://../assertions/tikz_thinking_length.py
      metric: thinking_length

derivedMetrics:
  - name: avg_renderable
    value: "renderable / __count"

  - name: avg_image_ssim
    value: "image_ssim / __count"

  - name: avg_image_ms_ssim
    value: "image_ms_ssim / __count"

  - name: avg_clip_similarity
    value: "clip_similarity / __count"

  - name: avg_siglip_similarity
    value: "siglip_similarity / __count"

  - name: avg_lpips_similarity
    value: "lpips_similarity / __count"

  - name: avg_dreamsim_similarity
    value: "dreamsim_similarity / __count"

  - name: avg_dists_similarity
    value: "dists_similarity / __count"

  - name: avg_crystalbleu
    value: "crystalbleu / __count"

  - name: avg_ted_similarity
    value: "ted_similarity / __count"

  - name: avg_relative_length_similarity
    value: "relative_length_similarity / __count"

  - name: avg_thinking_length
    value: "thinking_length / __count"


tests: file://../tests.py:generate_tests
